apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx-test
  name: nginx-test-rc
spec:
  replicas: 2
  selector:
    name: nginx-test
  template:
    metadata:
      labels:
        name: nginx-test
    spec:
      containers:
      - image: kaija/nginx_status
        name: nginx-test
        ports:
        - containerPort: 80
          name: http-server
          protocol: TCP
        - containerPort: 8080
          name: nginx-status
          protocol: TCP
      - image: fish/nginx-exporter
        name: nginx-exporter
        command: -nginx.scrape_uri=http://127.0.0.1:8080/nginx_status
        ports:
        - containerPort: 9113
          name: nginx-exporter
