apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    component: nginx
spec:
  type: LoadBalancer
  selector:
    component: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: exporter
    port: 9113
    protocol: TCP
    targetPort: exporter
